kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      pgconn:
        from_secret: PGCONN
    commands:
      - cd Test
      - dotnet restore
      - dotnet test
      - cd ../app
      - dotnet sonarscanner begin /k:"easv-devops_DHDroneSonar_AY2P7jVgEVvRW2O60D7G" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_c3e87cca1355afa06313497a6cd14a3947f4b965" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "../Test/coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="sqp_c0f14afa511ee77b44d73a1a693bd87505fc9978"
        