kind: pipeline
type: docker
name: integration

steps:
  - name: push to docker
    image: plugins/docker
    environment:
      pgconn:
        from_secret: PGCONN
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      dockerfile: app/Dockerfile
      context: ./app
      repo: donhundley/calculator
      tags:
        - latest 